name: learn_github_actions
on: [push]
jobs:
  check-bats-version: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: chmod +x ./init.sh
      - run: ./init.sh -v
      - run: ./init.sh -h
      - run: ./init.sh -q
      - run: ./init.sh --version 